; The order of display is as shown below
; The name of the index field is on the left
; The display name of the field is on the right
[Results]
;ss_name_1  = Model
ss_model = Model
;sm_name_43 = Format
sm_format = Format
;sm_name_2 = "Genre"
sm_genre  = Genre
; (Genre taxonomy)
; Labeled Type in $defaultFacetList
;sm_name_22 = "Legacy Resource Type"
sm_legacy_resource_type = "Legacy Resource Type"
; Not entirely clear how this differs or relates to Genre field above
;sm_field_subjects_name = "Subject (Name) EVALUATE"
;sm_field_subject = "Subject"
sm_subject = "Subject"
;sm_name_3 = "Subject (Geography)"
sm_subject_geographic = "Subject (Geography)"
sm_field_temporal_subject = "Subject (Temporal)
;sm_subject_temporal = "Subject (Temporal)
; currently not populated; nothing displayed in form
;sm_field_display_title = "Related Objects"
;TODO: Do we want Related Objects as a facet. (Field above is object title)
;sm_name_8 = "Related People"
sm_related_person = "Related People"
;sm_name_9 = "Related Places"
sm_related_place = "Related Places"
;sm_name_10 = "Related Organizations"
sm_related_organization = "Related Organizations"
;sm_name_11 = "Related Events"
sm_related_event = "Related Events"
;sm_field_linked_agent = "Linked Agents"
sm_linked_agent = "Linked Agents"
;sm_title_2 = "Archive Collection"
sm_collection = "Archive Collection"
;ss_name_23 = Contributing Library
ss_library = Contributing Library
;sm_name_20 = "Music Genre"
sm_music_genre = "Music Genre"
;sm_field_physical_form = "Physical Form"
sm_physical_form = "Physical Form"
;sm_name_13 = Research Level
sm_research_level = Research Level
;sm_field_research_type = Research Type
sm_research_type = Research Type
;sm_name_21 = Rights Creator
sm_rights_creator = Rights Creator
;sm_name_17 = Rights Holder
sm_rights_holder = Rights Holder
; undergraduate, masters

;sm_name_26 = Target Audience
; general, adult, preschool; is a boulder field

; Facets that will appear at the top of search results when the TopFacets
; recommendations module is used.  See the [TopRecommendations] section of
; searches.ini for more details.
[ResultsTop]
;none for now

; This section is reserved for special boolean facets.  These are displayed
; as checkboxes.  If the box is checked, the filter on the left side of the
; equal sign is applied.  If the box is not checked, the filter is not applied.
; The value on the right side of the equal sign is the text to display to the
; user.  It will be run through the translation code, so be sure to update the
; language files appropriately.
;
; Leave the section empty if you do not need checkbox facets.
;
; NOTE: Do not create CheckboxFacets using values that also exist in the
;       other facet sections above -- this will not work correctly.
[CheckboxFacets]

; These settings affect the way the [Results] facets are displayed
; If using facets at the top of search results you have more room for text.
[Results_Settings]
facet_limit = 120
; Rows and columns for table used by top facets
top_rows   = 2
top_cols   = 3

; These facets will be displayed as limiters on the advanced search search screen
[Advanced]

; These settings affect the way the [Advanced] facets are displayed
[Advanced_Settings]
facet_limit      = 120

;translated_facets[] =
;TODO: use for special filters that are applied. e.g. on the archive home page
translated_facets[] = bs_field_pika_shown_homepage
; There doesn't appear to be any facets that need translating. pascal 3/31/2026
; presumably, the nid_facets would though

;TODO: re-work & re-configure
nid_facets[] = its_node_id
nid_facets[] = itm_field_member_of
;nid_facets[] = itm_field_subject_general
;nid_facets[] = itm_nid_1
; integer version for 'member of'


;[Basic_Searches]

; This section defines which search options will be included on the advanced
; search screen.  All the notes above [Basic_Searches] also apply here.
;[Advanced_Searches]