A = A - Kindergarten
B = B - Kindergarten
C = C - Kindergarten
D = D - Kindergarten
E = E - Grade One
F = F - Grade One
G = G - Grade One
H = H - Grade One
I = I - Grade One
J = J - Grade One
K = K - Grade Two
L = L - Grade Two
M = M - Grade Two
N = N - Grade Three
O = O - Grade Three
P = P - Grade Three
Q = Q - Grade Four
R = R - Grade Four
S = S - Grade Four
T = T - Grade Five
U = U - Grade Five
V = V - Grade Five
W = W - Grade Six
X = X - Grade Six
Y = Y - Grade Six
Z = Z - Grade Seven & Eight
Z+=Z+ - High School/Adult