0 = Non Fiction
1 = Fiction
D = Fiction
E = Non Fiction
F = Fiction
H = Fiction
I = Non Fiction
J = Fiction
M = Fiction
P = Non Fiction
# Union Catalog Committee decision 2025-09-24, code Poetry as literary Form 'Non-Fiction'
S = Non Fiction
U = Unknown
Unknown = Unknown
* = Not Coded