<?php
/**
 * Copyright (C) 2020  Marmot Library Network
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *
 *
 * @category Pika
 * @author: Pascal Brammeier
 * Date: 7/10/2020
 *
 */


class GroupedWorkVersionMap extends DB_DataObject {
	public $__table = 'grouped_work_versions_map';
	public $groupedWorkPermanentIdVersion4;
	public $groupedWorkPermanentIdVersion5;
	public $missingFromCatalog;

	function keys(){
		return ['groupedWorkPermanentIdVersion4'];
//		return parent::keys(); // TODO: Change the autogenerated stub
	}

	static function getObjectStructure(){
		return [
			[
				'property'         => 'groupedWorkPermanentIdVersion4',
				'type'             => 'label',
//				'size'             => 36,
//				'maxLength'        => 40,
				'label'            => 'Grouped Work Id Version 4',
				'description'      => 'The id of the grouped work in previous version to match.',
//				'serverValidation' => 'validateDestination',
				'storeDb'          => true,
				'required'         => true,
			],
			[
				'property'         => 'groupedWorkPermanentIdVersion5',
				'type'             => 'text',
				'size'             => 36,
				'maxLength'        => 40,
				'label'            => 'Grouped Work Id Version 5',
				'description'      => 'The id of the grouped work in the current version to match the for the previous version id.',
//				'serverValidation' => 'validateSource',
				'storeDb'          => true,
				'required'         => true,
			],
			[
				'property'    => 'missingFromCatalog',
				'type'        => 'checkbox',
				'label'       => 'Missing from Catalog',
				'description' => 'Indicates there is no catalog entry for the grouped work id.',
				'storeDb'     => true,
//				'required'    => true,
			],
	];
	}

}