<?php
/**
 * Pika Discovery Layer
 * Copyright (C) 2020  Marmot Library Network
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *
 *
 * @category Pika
 * @author: Pascal Brammeier
 * Date: 1/13/2020
 *
 */

require_once ROOT_DIR . '/RecordDrivers/SideLoadedRecord.php';
class RBdigitalMagazineRecordDriver extends SideLoadedRecord {
	function getRecordType(){
		return 'RBdigitalMagazine';
		return parent::getRecordType(); // TODO: Change the autogenerated stub
	}

	public function getAccessOnlineUrl(User $patron)
	{
		return false;
	}

}
